import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function PlanResult({ plan }) {
  if (!plan) return null;

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-slate-100 overflow-hidden">
      <div className="bg-brand-600 p-6 text-white">
        <h2 className="text-2xl font-bold">Your Personalized AI Travel Plan</h2>
        <p className="opacity-90 mt-1">Generated by IBM watsonx.ai</p>
      </div>
      
      <div className="p-8 max-w-none prose prose-slate prose-headings:text-brand-900 prose-h1:text-3xl prose-h2:text-2xl prose-a:text-brand-600 hover:prose-a:text-brand-800">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {plan.plan_markdown}
        </ReactMarkdown>
      </div>
    </div>
  );
}
